### ISSUE TITLE
Актуализация перевода RBE

### ISSUE THREAD

**Issue by XX** [rust-lang-ru/community#1]
Текст русскоязычной версии RBE (Rust By Example book) значительно отстал от изменений в оригинале.

### Мотивация

Необходимо актуализировать перевод RBE и упростить процесс синхронизации изменений с оригиналом на будущее.

### Критерий успеха

Законченный и актуальный перевод RBE на русский язык, формат книги аналогичен оригиналу.

#### Исполнители

@XX

### Нерешённые вопросы

Возможно следует сделать форк репозитория исходной книги заново?
Где следует разместить этот новый репозиторий?

Кое-что обсуждали в этой ветке: https://forum.rustycrate.ru/t/dalnejshaya-sudba-rbe-i-perevod-drugih-knig/306

**Comment by Gordon-F** [comment]
Перед началом работы над задачей, неплохо было бы решить эту https://github.com/ruRust/rustycrate.ru/issues/266

**Comment by mkpankov** [comment]
Перенёс в "реализуется".

**Comment by ava57r** [comment]
правила работы с переводом определили, теперь надо начать работы по этой задаче.

**Comment by ava57r** [comment]
Давайте наметим план.

**Comment by ava57r** [comment]
Я предлагаю начать изменение на основе уже существующего репозитория в отдельных ветках.
- оригинал
- ветка перевода

текущий мастер пока не трогать, пока не пройдет вычитка более или менее объемная

**Comment by ava57r** [comment]
У меня доступа к репозиториям нет, кто будет помогать?

**Comment by mkpankov** [comment]
Дал доступ

**Comment by ava57r** [comment]
Книга переведена на `mdbook`.
Актуальность на 30 марта 2018.
Сейчас перевожу https://github.com/ruRust/rust-by-example-ru/pull/116

Я считаю основную задачу выполненной, а остальное детали.
Нужна помощь в переводе, а то скоро книга устареет и станет не актуальной.

**Comment by mkpankov** [comment]
Какой статус по итогам 2018? Всё удалось?

**Comment by ava57r** [comment]
Да, на MDbook перевели.
