### ISSUE TITLE
Передача: Gitter

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#10]
* Нужно модерировать чат самому или привлекать для этого других модераторов, и в целом следить что он работает

Список текущих админов во всех каналах:
* general:
  - Andrey Lesnikov @ozkriff
  - Nikita Baksalyar @nbaksalyar
  - Ilya Bogdanov @vitvakatu 
  - (почему меня тут нет, я не знаю, но права админа у меня всё ещё есть)

* easy:
  - Michael Pankov @mkpankov
  - Ilya Bogdanov @vitvakatu 

* offtopic:
  - Andrey Lesnikov @ozkriff
  - Nikita Baksalyar @nbaksalyar 

* gamedev:
  - Michael Pankov @mkpankov
  - Andrey Lesnikov @ozkriff 

* rust_book_ru:
  - Andrey Lesnikov @ozkriff
  - Michael Pankov @mkpankov 

* webdev:
  - Michael Pankov @mkpankov
  - Hanov Ruslan @hanovruslan
  - Konstantin Stepanov @kstep 

* rustycrate.ru:
  - Andrey Lesnikov @ozkriff
  - Michael Pankov @mkpankov 

* algo:
  - Michael Pankov @mkpankov
  - Alexander Kuvaev @Vinatorul 

* infosec:
  - Michael Pankov @mkpankov
  - Sergey Noskov @Albibek

**Comment by kpp** [comment]
Добавь меня в general, easy и offtopic.

**Comment by boozook** [comment]
Прошу добавить меня в easy, general, gamedev. Можно вообще во все.

**Comment by mkpankov** [comment]
Добавил вас
