### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#11]
* Поддержка страницы для сбора денег

Передать её можно только сменой email на другой, и передачу пароля.

Физически аккаунт останется тем же самым.

Поскольку он связан с моим банковским счётом и мной как налоговым резидентом, передавать его мне кажется не слишком разумно.

Предлагаю создать новую страницу или организовать другой способ сбора денег. Всех текущих патронов я проинформирую что мой Patreon больше не собирает деньги в пользу сообщества, и укажу куда надо перенаправить поддержку.

**Comment by funkill** [comment]
Аккаунт создан, необходима настройка. Поле Patreon page URL" может блокироваться задачей #19

**Comment by funkill** [comment]
Поставил лого, url и название, выбранные на опросе из задачи #19.

**Comment by mkpankov** [comment]
15 декабря уберу сообщество со своего Patreon

**Comment by ava57r** [comment]
Создал https://opencollective.com/rust-lang-ru

**Comment by ava57r** [comment]
Задачу решили? Согласны?

**Comment by funkill** [comment]
По всем вопросам обращаться к @funkill или @ava57r
