### ISSUE TITLE
Передача: твиттер

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#12]
* Ведение твиттера сообщества

Передача через смену email на новый и передачу пароля.

**Comment by ozkriff** [comment]
![image](https://user-images.githubusercontent.com/662976/55402162-6c5e1200-555b-11e9-87df-a9963b951614.png)

Я состою в tweetdeck'овской команде, но админом самой учетки не являюсь. Для роли "на подхвате" этого достаточно, наверное, но у нас же нет добровольца на поддержку твитера?

**Comment by XX** [comment]
@mkpankov Мой твиттер: https://twitter.com/freecoder_xx
Или для добавления в админы нужен именно e-mail?

**Comment by mkpankov** [comment]
@XX да, твитдек это какая-то штука сбоку, я поменяю email в аккаунте на твой и дам тебе пароль

**Comment by XX** [comment]
@mkpankov Еще нет?

**Comment by mkpankov** [comment]
Всё передеали
