### ISSUE TITLE
Передача: Facebook

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#13]
* Ведение страницы сообщества в Facebook

Передача через добавление фейсбук-аккаунта нового админа.

**Comment by XX** [comment]
@mkpankov Мой FB: https://www.facebook.com/profile.php?id=100008483864085

**Comment by ozkriff** [comment]
Давайте меня "на подхват" тоже - https://www.facebook.com/ozkriff

**Comment by mkpankov** [comment]
@XX @ozkriff  сделал вас админами, подтверждайте
