### ISSUE TITLE
Передача: Вконтакте

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#14]
* Ведение страницы сообщества Вконтакте

Передача через добавление аккаунта нового админа.

**Comment by XX** [comment]
@mkpankov Можешь добавить мой аккаунт: https://vk.com/freecoder_xx

**Comment by mkpankov** [comment]
@XX принимай приглашение друзья и вступай в группу

**Comment by ozkriff** [comment]
Меня в социалки покидай тоже, буду на подхвате, если чего.

**Comment by mkpankov** [comment]
Добавил @XX админом

**Comment by XX** [comment]
@ozkriff А какой у тебя VK ID?

**Comment by ozkriff** [comment]
https://vk.com/ozkriff

**Comment by XX** [comment]
Добавил.

**Comment by ava57r** [comment]
Добавляйте меня тоже.
https://vk.com/id2918671
