### ISSUE TITLE
Передача: Телеграм

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#15]
* Ведение телеграм-канала сообщества

Передача через добавление аккаунта администратора канала.

**Comment by ozkriff** [comment]
http://t.me/ozkriff - докидывайте меня, буду на подхвате если чего

**Comment by mkpankov** [comment]
@ozkriff добавил тебя

**Comment by boozook** [comment]
Принимаю. Добавляйте меня, пожалуйста. `@fzzzr`

**Comment by mkpankov** [comment]
Добавил
