### ISSUE TITLE
Передача: GitHub

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#16]
* Высокоуровневое курирование проектов в сообществе (управление репозиториями, выдача прав)

Передача через добавление админа в организацию ruRust.

**Comment by ozkriff** [comment]
Как минимум я и @XX числимся owner'ами сейчас.

**Comment by funkill** [comment]
Надо добавить @funkill и @fzzr-

**Comment by XX** [comment]
@funkill - сделал owner, @fzzr- выслал инвайт.

**Comment by boozook** [comment]
Можно закрыть. Все [приняли](https://github.com/orgs/ruRust/people?utf8=✓&query=+role%3Aowner) приглашения.
