### ISSUE TITLE
Составить список возможных доменов для сайта и провести голосование

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/community#18]
Имеющиеся возможные домены:
rurust.rs
rustycrate.ru

**Comment by funkill** [comment]
> @LooMaclin: Нужно собрать все варианты и сделать опрос среди участников сообщества

**Comment by mkpankov** [comment]
У меня ещё есть
rust-lang.ru

**Comment by LooMaclin** [comment]
@mkpankov 
![image](https://user-images.githubusercontent.com/10957765/60590727-6586ab80-9da5-11e9-822d-8890998730ac.png)

**Comment by mkpankov** [comment]
@LooMaclin и что я должен тут увидеть?

**Comment by funkill** [comment]
@mkpankov Скорее всего так: ты владелец rust-lang.ru?

**Comment by mkpankov** [comment]
Да

**Comment by funkill** [comment]
Опрос проведён. rust-lang.ru (79.5%, 66 человек)
<details><summary>Результаты</summary>

![site_url](https://user-images.githubusercontent.com/4323287/63161962-18dff280-c02a-11e9-9dfa-2f8cf6dc4fdc.jpg)

</details>
