### ISSUE TITLE
Составить список возможных имён для организации и провести голосование

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/community#19]
ruRust
rust-lang-ru
rustlangRU

**Comment by funkill** [comment]
> @LooMaclin: Нужно собрать все варианты и сделать опрос среди участников сообщества

**Comment by ava57r** [comment]
Rust Russia
Russia Rust

**Comment by ava57r** [comment]
Кстати ты @funkill  логотип поставил на ruRust от оригинала
А что если сделать такую же шестерню, но там RU внутри =)

**Comment by funkill** [comment]
Ну, у [японцев](https://github.com/rust-lang-ja/) и [китайцев](https://github.com/rust-lang-cn/) тоже от оригинала стоит) Но они всё же больше именно как организации с переводами позиционируются.

Если будем менять, то уже после выбора названия

**Comment by ava57r** [comment]
Опрос делаем?

**Comment by funkill** [comment]
Опрос проведён.

Результаты:
- URL организации на Github: rust-lang-ru (61.4%, 51 человек)
- Название организации на Github: Russian Rust Community (51.8%, 43 человека)
- Логотип - официальный (55.4%, 46 человек)

В комментариях к опросу указывалось, что в сообществе есть люди не только из России, и в итоге после [обсуждений](https://github.com/ruRust/meeting-minutes/blob/master/2019/2019-08-13.md#результаты-опросов) в качестве названия организации было выбрано "Rust - русскоязычное сообщество".

<details><summary>Результаты</summary>

![logo](https://user-images.githubusercontent.com/4323287/63161993-25644b00-c02a-11e9-9259-957152a6b05a.jpg)
![org_name](https://user-images.githubusercontent.com/4323287/63161994-25644b00-c02a-11e9-86e3-9e4064177ebf.jpg)
![org_url](https://user-images.githubusercontent.com/4323287/63161995-25644b00-c02a-11e9-9d16-7d5c7d1252d9.jpg)

</details>
