### ISSUE TITLE
Список интересных ресурсов с небольшим резюме.

### ISSUE THREAD

**Issue by chtotut** [rust-lang-ru/community#2]
Создание списка интересных ресурсов с небольшим описанием (резюме).

### Мотивация

Довольно много интересных материалов выходит по Rust. И охватить их все - довольно емкий по времени процесс. Более того, иногда материал разочаровывает и не стоют потраченного времени.
Было бы отлично, если бы существовало нечто, где можно было бы увидеть список последних интересных материалов с небольшими резюме по ним.
Пример:
[Перевод названия статьи](ссылка)
Отличная статья по внутреннему устройству и механизмам tokio. Написана одним из авторов фреймворка. Рекомендуется к прочтению.

### Критерий успеха

Когда подавляющая часть интересных событий в жизни языка и его окружения будут охватываться этим списком.

### Ресурсы

Площадка, где будут размещаться ссылки с резюме.
В первом приближении это может быть канал в гиттере, где не будет никаких более сообщений, кроме такого вида описания ресурсов.

#### Исполнители

Потребуется активность от сообщества и модератор для контроля.

**Comment by XX** [comment]
@chtotut Список ссылок, подобный этому? https://github.com/ctjhoa/rust-learning
Правда в нем нет кратких резюме.

**Comment by mkpankov** [comment]
Реддит подходит? У нас есть свой русскоязычный.

**Comment by mkpankov** [comment]
@chtotut нужна информация от тебя.

**Comment by mkpankov** [comment]
Если до 25 февраля обсуждение завершится ничем, идея не будет принята в реализацию.

**Comment by ozkriff** [comment]
По мне - описанную задачу и правда реддит вполне может выполнять. Вопрос только в том что никто им не пользуется по факту.

**Comment by mkpankov** [comment]
Не принято из-за недостатка информации.
