### ISSUE TITLE
Августовская встреча сообщества в Москве

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/community#22]
### Критерий успеха

Провести встречу сообщества 16-18 августа.

#### Исполнители

@funkill @andreevlex 

### Нерешённые вопросы

Место, время.

**Comment by ava57r** [comment]
Предлагаю 16 - 17.
В воскресенье точно ни кто не придёт.
Если пятница то с 19 - 00.
Суббота с 15, 16 часов.

**Comment by ava57r** [comment]
Место
https://zoon.ru/msk/restaurants/antikafe_geek_square_na_bolshoj_novodmitrovskoj_ulitse/

**Comment by kpp** [comment]
> Место, увы, закрылось

**Comment by ava57r** [comment]
Ну вот =(

@kpp 
Предложения?

**Comment by ava57r** [comment]
http://comein-kafe.ru/ можно сюда.

**Comment by funkill** [comment]
https://www.meetup.com/Rust-%D0%B2-%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B5/events/263814601/

**Comment by funkill** [comment]
Сходка прошла успешно. Я насчитал 27 одновременных человек. По статистике от @kpp было 40+ человек
