### ISSUE TITLE
Реорганизация команд и участие в жизни Github-организации

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/community#26]
Всем привет!

В начале года @mkpankov сообщил, что [уходит с поста организатора](https://forum.rustycrate.ru/t/ya-uhozhu-s-posta-organizatora/721), после чего была [собрана инициативная группа](https://forum.rustycrate.ru/t/potenczialnyj-spisok-komandy-soobshhestva/728), взявшая управление на себя. 

После изучения текущих команд было решено обратиться к их участникам (вам) и узнать, есть ли у вас желание участвовать в развитии сообщества и данной организации? И если есть, то в каком направлении хотели бы участвовать?

Также мы собираемся реорганизовать текущие команды и, соответственно, удалить из них тех людей, которые больше не будет участвовать в работе этих команд. Мы хотели переместить их в новую команду (по аналогии с [Rust team alumni](https://www.rust-lang.org/governance/teams/alumni)), но в силу того, что участники данных команд не отображаются и команде требуется лидер, было решено отказаться от этой идеи. Мы пока что в раздумьях, как отразить ваш вклад в развитие.

Из самой организации мы никого удалять не собираемся.

@BORN2LOSE
@defuz
@Gordon-F
@kstep
@ozkriff 
@serejkaaa512 
@vessd

**Comment by vessd** [comment]
На данный момент не собираюсь участвовать в чём-либо.

**Comment by wmorgue** [comment]
Привет!

Занят iOS 🍏 разработкой.

**Comment by kstep** [comment]
Отошёл от организаторских дел. В ближайшее время участвовать не буду. Может в будущем году что-то изменится.

**Comment by funkill** [comment]
@defuz @Gordon-F @serejkaaa512 Завтра удаляю из команд. Если есть возражения, просьба написать об этом.
