### ISSUE TITLE
Лекция в МФТИ

### ISSUE THREAD

**Issue by funkill** [rust-lang-ru/community#33]
У @andreevlex есть выход на МФТИ и там можно будет выступить с лекцией про Rust

**Comment by funkill** [comment]
- Что от нас ждут? Тема (примерное направление) или общий/вводный?
- Для кого? Студенты первокурсники или 4-5 курс мехмата? Или там могут быть кто угодно? Или они там приглашают школьников?
- Формат: доклад, именно лекция какая-то или ещё что?
- Сколько времени нам выделяют?
- Техническое оснащение (экран/проектор, микрофон и прочее)
- Сколько человек будет на лекции?
- Сколько докладов/лекций мы можем провести?

После этого сможем приготовить список тем, на которые сможем сделать доклад

**Comment by kpp** [comment]
* длительность доклада, даты

**Comment by ava57r** [comment]
Привет.
думаю темы подойдут обзорные.
Будут студенты МФТИ и выпускники.

Остальные вопросы вытекают из того что мы сможем рассказать.

**Comment by ava57r** [comment]
Я предполагаю, что если устраивать, то после нового года.

**Comment by ava57r** [comment]
Не буду организовывать лекцию.
Мой контакт там больше не работает.
Отбой.
