### ISSUE TITLE
Митап 1 ноября 2019 Мск

### ISSUE THREAD

**Issue by ava57r** [rust-lang-ru/community#38]
# План проведения встречи разработчиков Мск в ноябре 2019.

Дата проведения: 1 ноября 2019.
Место: Москва Сити, Башня Федерация, 54-й этаж.

Планируемые темы докладов:
1. Scrubs that grow. TL;DR: как сделать расширяемые типы суммы, которые будут проверяться компилятором.
2. Ноу-хау команды Broxus обзорный доклад о backend проекта.

**Comment by ava57r** [comment]
@vorot93 какой доклад у тебя будет примерно?

**Comment by vorot93** [comment]
@andreevlex Broxus: кто мы такие и ноу-хау нашего backend-а в production.

**Comment by ava57r** [comment]
Обсудили в чате.
Будут доклады от команды Broxus и Scrubs that grow.
