### ISSUE TITLE
Неформальные встречи разработчиков (Мск)

### ISSUE THREAD

**Issue by ava57r** [rust-lang-ru/community#4]
### Мотивация

Хотелось бы чаще встречаться.
Чаты хорошо, но личного общения ни кто не отменял.
Представителям python сообщества удается устраивать встречи минимум 1 раз в 2 месяца, как это им удается?

### Критерий успеха

Три официальных митапа в год.

### Ресурсы

Необходимы спонсоры.

**Comment by mkpankov** [comment]
Речь идёт про встречи на 10-20 человек? Или про митапы как в ЛК?

**Comment by XX** [comment]
А может стоит организовывать не только митапы, но и просто неформальные встречи? Типа заседания RPG (Rust programmers group). Выбирать доступные места (кафе, коворкинги, просто на природе)) и регулярно устраивать неформальное общение Rust-разработчиков. Например, раз или два раза в месяц. Что скажете?

**Comment by ozkriff** [comment]
@XX Я бы в Питере не против таких встреч был бы.

**Comment by XX** [comment]
@ozkriff Тогда давайте организуем! Я тоже в СПб :)

**Comment by mkpankov** [comment]
Нужно выяснить про что изначальная идея и разделить их в случае, если имеются ввиду большие митапы.

@andreevlex проясни пожалуйста.

**Comment by ava57r** [comment]
Я изначально говорил об официальных встречах как в офисе компании Касперского. 

Неформальной встречи я думаю трудно будет курировать именно сообществу,да и спонсоры на это не найдутся.

**Comment by mkpankov** [comment]
Тогда необходимые ресурсы - это в первую очередь не спонсоры, а докладчики и организаторы.

**Comment by mkpankov** [comment]
@XX @ozkriff вашу тему про неформальные встречи предлагаю создать как отдельную идею.

**Comment by mkpankov** [comment]
Возможный формат такой: проводим в Лаборатории Касперского, я со-организатор и помогаю по необходимости.

### Ищем организатора

От организатора требуется:
- найти докладчиков
- выбрать дату и время
- общаться с представителем площадки (мой коллега) по всем вопросам относительно техники, помещения, трансляции и т.д.
- общаться с докладчиками и удостовериться, что все готовы будут выступить
- по необходимости, порепитировать доклады с докладчиками
- быть на площадке во время мероприятия

Альтернативно, можно проводить не в ЛК. Несколько контактов возможных площадок я могу дать.

### Ищем докладчиков

Если кто-то хочет в этом году выступить, это отличная возможность. У нас тёплая ламповая атмосфера и мы помогаем с подготовкой к докладу.

<hr/>

Пишите сюда, мне [в личку на Gitter](https://gitter.im/mkpankov), или [на почту](mailto:rustycrate@michaelpankov.com).

**Comment by XX** [comment]
Отдельная задача для неформальных встреч: https://github.com/ruRust/community/issues/6

**Comment by mkpankov** [comment]
Двигаю в "Реализуется". На данный момент реализация - это поиск организатора и докладчиков.

**Comment by ava57r** [comment]
Наблюдая за реализацией #6 хочу предложить подумать как организоваться в Москве, а в последствии и других городах. Может создать как отдельную задачу?

**Comment by mkpankov** [comment]
@andreevlex я вынесу свой комменатрий про формальные митапы в отдельную задачу.

Про встречи "как в СПб" - кто готов пригласить к себе людей?

Нужно место, где можно бесплатно собираться.

**Comment by mkpankov** [comment]
Про формальные митапы здесь: #7. Здесь остаётся обсуждение небольших "душевных" встреч в Мск.

**Comment by mkpankov** [comment]
Пробный неформальный митап: https://forum.rustycrate.ru/t/neformalnaya-vstrecha-rust-razrabotchikov-moskva-5-aprelya-19-30/348/1

**Comment by ava57r** [comment]
Вот в Москве была [Неформальная встреча в Storiqa #2](https://www.meetup.com/Rust-%D0%B2-%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B5/events/250580863/?comment_table_id=257127239&comment_table_name=reply), а если будет следующая, может надо подумать о общем векторе.
Например есть сообщество и есть вопросы которые можно обсудить или какие то крупные темы:
- "Раст для вэб"
- "Кривая обучения языку".

Это не догма, но когда трындим про Scala =)

Вот есть ребята Moscow Programmers Club http://meetu.ps/c/2CFGt/Fjc3K/d на Meetup, у них есть вектор для каждой встречи и обсуждение в кулуарах в достатке.

**Comment by mkpankov** [comment]
Я не был и мне тяжело судить. Если проблема с очень большими отсутплениями от темы, то стоит минимально модерировать обсуждение. С другой стороны, не стоит очень формально прерывать людей. Отступления от темы - это нормально.

**Comment by ava57r** [comment]
@mkpankov не, в этот раз мы четко были поглощены обсуждением темы доклада.
Я на перспективу.

**Comment by ava57r** [comment]
Я не столько про модерацию.
Я про то что мы анансируем тему для обсужения как главную (Указываем цель встречи).
Модерацией и прирыванием людей не хотел и не хочу заниматься =). Пусть приходят и общаются на любые темы.
Да встреча не формальная, но лейтмотив должен присутствовать.
