### ISSUE TITLE
Митап  Мск апрель 2020

### ISSUE THREAD

**Issue by ava57r** [rust-lang-ru/community#47]
# План проведения митап online апрель 2020.

Дата проведения: 24 апреля 2020.
Онлайн формат.

Темы докладов:
1. Так ли нужно запускать прошивку на самом устройстве.
2. Способы обработки ошибок.

**Comment by funkill** [comment]
Так ли нужно запускать прошивку на самом устройстве: https://www.youtube.com/watch?v=NCE4w42hb7o
Способы обработки ошибок: https://www.youtube.com/watch?v=QCZXc5MyPVU
