### ISSUE TITLE
Разработать документ регламентирующий правила синхронизации переводов книг

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#5]
Нужен документ с описанием процесса перевода.

### Мотивация

Нужен стандартный процесс, упрощающий перевод и отслеживание изменений в оригинале.

### Критерий успеха

Есть документ, в котором описано:
* Как синхронизация переводов производится с использованием 2-х веток с оригиналом и переводом.
* Как сравнение переводов производится по diff файла, а не diff commits.

Документ - это Markdown-страница у нас на сайте, и на неё есть ссылка в "Материалы сообщества".

### Ресурсы

Автор документа с описанием процесса.

### Нерешённые вопросы

Нет

**Comment by mkpankov** [comment]
Нужно для:

https://github.com/ruRust/community/issues/3
https://github.com/ruRust/community/issues/1

**Comment by mkpankov** [comment]
Кто возьмётся? Критическая задача. @vitvakatu @Gordon-F @andreevlex

**Comment by ava57r** [comment]
Я готов участвовать.

**Comment by mkpankov** [comment]
@andreevlex тут надо не столько "участвовать", сколько сесть и написать документ, и сделать PR. Если готов, начинай

**Comment by ava57r** [comment]
@mkpankov Куда писать документ?
1. https://github.com/ruRust/rustycrate.ru
2. https://github.com/ruRust/community

**Comment by mkpankov** [comment]
rustycrate.ru

**Comment by wmorgue** [comment]
Реализовано в https://github.com/ruRust/rustycrate.ru/pull/277

**Comment by mkpankov** [comment]
Всем спасибо, особенно @andreevlex !
