### ISSUE TITLE
Неформальные встречи разработчиков (СПб)

### ISSUE THREAD

**Issue by XX** [rust-lang-ru/community#6]
Предлагаю организовывать неформальные встречи Rust-разработчиков, что-то вроде заседаний RPG (Rust programmers group). Выбирать доступные места (кафе, коворкинги, просто на природе) и регулярно устраивать неформальное общение Rust-разработчиков. Например, раз или два раза в месяц.

### Мотивация

Требуется живое общение Rust-разработчиков, не скованное форматом митапа.

### Критерий успеха

Встречи проводятся регулярно, общение так или иначе связано с Rust, участники встреч вполне ими довольны :)

### Ресурсы

Самое главное - это найти места для встреч. В идеале - с электричеством и интернетом.
Второе - продумать организацию питания на встречах.
Также требуются энтузиасты-организаторы таких встреч.

#### Исполнители

@XX мог бы участвовать в организации встреч в СПб. Возможно также и @ozkriff 

#### Материальные ресурсы

Необходимы помещения для встреч, с электричеством и интернетом.

**Comment by ozkriff** [comment]
про места - может в каких-нибудь антикафе, где не особо шумно? надо будет поискать что не слишком далеко от метро. речь идет о выходных или вечере рабочих дней?

**Comment by XX** [comment]
@ozkriff Для меня - точно лучше на выходных (чтобы было хотя бы часа 4 на общение). Но удобно ли это другим потенциальным участникам?

Насчет мест. Кроме кафе, можно еще подумать о библиотеках и ВУЗах.

**Comment by ozkriff** [comment]
https://gitter.im/ruRust/offtopic?at=5a9124e9a2194eb80da7eee9

vlad20012:
> Можем в офисе JetBrains собираться хоть иногда, хоть регулярно. Тут места валом (особенно по выходным) и вход почти свободный. Я тут с Либертарианцами в настолки играю, например https://www.google.ru/maps/search/JetBrains/@59.9420981,30.2929742,17.25z

**Comment by vitvakatu** [comment]
Я тоже в деле, могу помочь с организацией

**Comment by vlad20012** [comment]
Предлагаю собираться в [офисе JetBrains](https://jetbrains.ru/company/offices/#city=spb) на В.О. ([Университетская наб., 7-9-11 к. 5А](https://www.google.ru/maps/search/JetBrains/@59.9420981,30.2929742,17.25z) вход с Кадетской линии)

Чай/кофе/электричество/интернет в наличии :)

Алгоритм организации тут простой: за несколько (3-10) дней до планируемой встречи пишите мне что хотите в такой-то день/время собраться. Соответственно, если у меня нет каких-то особых планов на этот день, то все ок, в ином случае обсуждаем другой день. А в общем случае мне норм и по выходным, и по будням, и в любое время :)

Единственное что неплохо бы знать примерное количество человек. Если 5-10, то все вообще просто. Если больше - нужно 7й этаж уже занимать. Короче неплохо бы что-то вроде гугл-формочки регистрации на встречу приладить.

Еще предлагаю создать отдельный чатик сходок и обсуждать уже там все подробности непосредственно с теми, кого это интересует.

**Comment by mkpankov** [comment]
Т.к. здесь решены практически все вопросы, двигаю сразу в "Реализуется".

**Comment by mkpankov** [comment]
В качестве группы для организации предлагаю использовать [Meetup](https://www.meetup.com/ru-RU/Rust-%D0%B2-%D0%9F%D0%B8%D1%82%D0%B5%D1%80%D0%B5)

**Comment by ozkriff** [comment]
Ну что ж, давайте тогда назначим первую сходку на это воскресение - 4 марта - в jetbrains на час дня.

**Comment by ozkriff** [comment]
@mkpankov кинешь объявление по социалкам?

**Comment by mkpankov** [comment]
Создавайте Meetup, кину ссылку на него сразу. Времени мало

**Comment by mkpankov** [comment]
Назначил @ozkriff и @vitvakatu соорганизаторами на Meetup в СПб. Жду страницу митапа 4го марта, и кину объявление

**Comment by mkpankov** [comment]
Если нужно добавить кого-то ещё, напишите пожалуйста

**Comment by ozkriff** [comment]
@mkpankov мы тут сейчас подумали-обсудили и, наверное, не будем первый раз кроме чата трубить - человек пять-семь из гиттера уже хотят прийти, для пробной встречи хватит.

А в следующий раз уже нормально на meetup.com заведем все. Ну и социалки тогда же.

**Comment by mkpankov** [comment]
Понял, давайте

**Comment by sergeysova** [comment]
Было бы неплохо звать людей из чата https://t.me/rustlang_ru

**Comment by vitvakatu** [comment]
@sergeysova на первую сходку звали оттуда, несколько человек было. Не вижу особой проблемы, большая часть анонсов постится во все чаты.

**Comment by ava57r** [comment]
А почему только СПб? =)

**Comment by vitvakatu** [comment]
@andreevlex если есть желание организовать в других городах - you're welcome, как говорится. Мы (@vitvakatu, @ozkriff, @vlad20012, и @XX) проживаем в СПб, поэтому логично, что мы собираем людей именно там :)

**Comment by mkpankov** [comment]
2 встречи прошло, будем считать, что реализовано? Отслеживать и обсуждать в задаче больше нечего

**Comment by XX** [comment]
> Критерий успеха
>
> Встречи проводятся регулярно, общение так или иначе связано с Rust, участники встреч вполне ими довольны :)

По этому критерию - вполне себе реализовано )
