### ISSUE TITLE
Формальные митапы с докладами (Мск)

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#7]
На данный момент я больше не готов выступать основным организатором больших митапов с докладчиками в Лаборатории Касперского. Однако я могу быть соорганизатором, и площадка в ЛК всё ещё доступна. В связи с этим, мы ищем организатора и докладчиков для продолжения "больших" митапов сообщества.

### Мотивация

Периодические большие митапы несут знания и служат площадкой для обсуждения идей, высказанных в докладах. Есть аудитория, которая регулярно приходит слушать доклады. В формате с докладами соотношение "польза-душевность" сдвинуто в сторону "пользы".

### Критерий успеха

Проведён 1 большой митап на любой площадке с 50+ участниками и 2+ докладами.

### Ресурсы

Необходимо: 
* место на 50+ человек, с бесплатным входом
* организатор митапа
* 2 докладчика

Желательно: чтобы там были напитки/перекусы, желательно бесплатные, трансляция докладов в интернет.

### Нерешённые вопросы

Кто станет организатором, кто готов сделать доклады, на какой площадке (если в ЛК не устроит).

**Comment by mkpankov** [comment]
Возможный формат такой: проводим в Лаборатории Касперского, я со-организатор и помогаю по необходимости.

Альтернативно, можно проводить не в ЛК. Несколько контактов возможных площадок я могу дать. Спонсоры при этом наверняка не понадобятся.

# Ищем организатора

От организатора требуется:

* найти докладчиков
* выбрать дату и время
* общаться с представителем площадки (мой коллега) по всем вопросам относительно техники, помещения, трансляции и т.д.
* общаться с докладчиками и удостовериться, что все готовы будут выступить
* по необходимости, порепитировать доклады с докладчиками
* быть на площадке во время мероприятия

# Ищем докладчиков

Если кто-то хочет в этом году выступить, это отличная возможность. У нас тёплая ламповая атмосфера и мы помогаем с подготовкой к докладу.

<hr/>

Пишите сюда, мне [в личку](https://gitter.im/mkpankov) на Gitter, или [на почту](mailto:rustycrate@michaelpankov.com).

**Comment by ava57r** [comment]
Что ни кто не отозвался?

**Comment by mkpankov** [comment]
Незапланированно сделали международную конференцию RustRush. Закрываю за 2018.
