### ISSUE TITLE
Передача: форум

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#8]
* Обновление движка. Чаще всего делается кнопкой в веб-интерфейсе, но может сломаться. Потребуется зайти на сервер по SSH и чинить. За 3 года ломалось 1 или 2 раза. Потребовалось сделать бэкап данных из PostgreSQL в Docker, проапгрейдить PostgreSQL, и раскатать бэкап. Это делалось по инструкции от Discourse в результате гугления проблемы. Итого потратил часа 3.
* Оплата хостинга
* Оплата домена (раз в год или реже)

Потребуется изначально развернуть/перенести сервис с существующего сервера (с моей помощью)

**Comment by ozkriff** [comment]
Я так понимаю, я и @kpp вызываемся сюда.

@mkpankov в какой форме тебе удобней информацию передавать?

Тем более что там как раз устарел образ системы и как надо зайти руками сходить по ssh.

**Comment by mkpankov** [comment]
Разворачивайте сервак, деплойте туда дискурс из официального докера, я выдам вам бэкап нашего инстанса, импортируем его и всё. Должно быть наиболее удобно.

**Comment by kpp** [comment]
А почему нельзя передать инстанс сервака как есть?

**Comment by mkpankov** [comment]
Узнаю у поддержки, можно ли.

Но вообще научиться его деплоить неплохо с т.з. хотя бы минимально представлять, как его админить.

**Comment by mkpankov** [comment]
Поддержка ответила что сервер передать нельзя.

**Comment by kpp** [comment]
Передали. Закрываем?
