### ISSUE TITLE
Передача: сайт

### ISSUE THREAD

**Issue by mkpankov** [rust-lang-ru/community#9]
* Обновление сертификатов TLS. Сейчас оно не автоматизировано, но делается certbot-auto за 1 минуту.
* Оплата хостинга.

* Оплата домена (раз в год или реже)

Потребуется изначально развернуть/перенести сервис с существующего сервера (с моей помощью)

**Comment by vitvakatu** [comment]
Получается, я и @funkill вызываемся на это.

@mkpankov отписал тебе в телеграме

**Comment by mkpankov** [comment]
Поговорили в телеграме, надо будет отдать скрипт и конфиг nginx когда вы поднимете сервер.

Для передачи домена нужен мне нужно будет знать аккаунт в reg.ru (номер договора), полное ФИО и email или телефон.

**Comment by kpp** [comment]
Запущен трансфер домена на меня

**Comment by kpp** [comment]
Передали. Закрываем?
